### ISSUE TITLE
TextMateAnalyzer does not work reliably when theme is read from background

### ISSUE THREAD

**Issue by tyron12233** [Rosemoe/sora-editor#152]
Using theme and TextMate grammars involves reading files. To keep the UI thread smooth, I moved these operations into a background thread.

With this done, the TextMate analyzer will occasionally not work. (All spans returned are white). Any further attempt to edit the text will throw an exception. [Stack trace here](https://pastebin.com/rYGPD1q2)

Minimal reproduceable project: [Github repo](https://github.com/tyron12233/SoraEditor-Bug-Report)

Steps to reproduce:
- Run and build the APK
- If the editor text are all white, the bug has occured.
- If not, rotate the device to force activity recreation until the text turns white.

**Comment by Rosemoe** [comment]
I haven't got why it is happening. I'll continue to track the bug when I have time...

**Comment by Rosemoe** [comment]
Please check whether 0.10.4 has the problem. If it is solved, close this issue.

**Comment by tyron12233** [comment]
Seems to have been fixed now, thanks
