### ISSUE TITLE
Symbol Pair Match on composing text

### ISSUE THREAD

**Issue by tyron12233** [Rosemoe/sora-editor#155]
When on a composing text (The text marked with underline while editing), editor features that depend on the length of the inserted text will not work. These are features like indent handlers and symbol pair match.

To reproduce, type a word and then follow it with a symbol pair without space.
```
SomeClass(
```

Expected behavior:
```
SomeClass() <- End pair inserted
```

Additional info:
Upon debugging, this is due to `commitText` on `BaseInputConnection` including the whole previous composing text and then the real inserted text. When you insert a symbol, the composing text is deleted and re inserted again, but the symbol pair match checks if the inserted text's length is 1 so this current approach would not work.

**Comment by tyron12233** [comment]
Instead of deleting the composing text and reinserting it again, maybe its better to get the difference from the previous composing text to the new committed text and then perform insert and delete operations on that.

**Comment by Rosemoe** [comment]
It's fixed in the newest commit
