### ISSUE TITLE
Incorrect cursor display position on Android 9 or below

### ISSUE THREAD

**Issue by zhxzkhz** [Rosemoe/sora-editor#156]
用的 sora-editor-0.10.8 里面 自带的TestActivity
![image](https://user-images.githubusercontent.com/82936352/158931134-9f851250-a3d4-4bfc-a452-469be6305230.png)

**Comment by Rosemoe** [comment]
![Screenshot_2022-03-18-12-19-31-517_io github rosemoe sora app](https://user-images.githubusercontent.com/28822819/158936845-846457ca-8d2a-45e6-ac98-315ad6b7ee19.jpg)
理论上不会出现这个问题。最好把字体提取出来发我。

**Comment by zhxzkhz** [comment]
> ![Screenshot_2022-03-18-12-19-31-517_io github rosemoe sora app](https://user-images.githubusercontent.com/28822819/158936845-846457ca-8d2a-45e6-ac98-315ad6b7ee19.jpg) 理论上不会出现这个问题。最好把字体提取出来发我。

我这没设置字体，使用的系统默认，这个输入时光标是没有任何问题的，但是输入后，光标往前移，就会发现问题

**Comment by Rosemoe** [comment]
来个演示视频 我复现不了
最好把系统字体提取发我

**Comment by zhxzkhz** [comment]
> 来个演示视频复现不能 最好把我的系统提取发给我

https://user-images.githubusercontent.com/82936352/158938940-50009813-19e7-4b31-92d7-63aa23b9eff3.mp4

**Comment by Rosemoe** [comment]
字体是Roboto吗

**Comment by zhxzkhz** [comment]
> 字体是Roboto吗

没设置字体，应该是采用的默认的，不确定

**Comment by Rosemoe** [comment]
你自己设备Android版本多少

**Comment by zhxzkhz** [comment]
> 




> 你自己设备Android版本多少

安卓9，模拟器是安卓7，也出现这情况

**Comment by Rosemoe** [comment]
行儿，我后面再看

**Comment by zhxzkhz** [comment]
> 你自己设备Android版本多少

![image](https://user-images.githubusercontent.com/82936352/159117279-fc8e3053-eb7c-4f81-98ce-f0631bf39318.png)
![image](https://user-images.githubusercontent.com/82936352/159117295-571919aa-db75-4ec2-a086-bd270cc7b6ff.png)

**Comment by Rosemoe** [comment]
我的Android 11上复现不了

**Comment by zhxzkhz** [comment]
> 我的Android 11上复现不了

安卓10 测试也没出现这问题

**Comment by Rosemoe** [comment]
可能是API问题。我用了一个在Android 10(API 29)才更改为公开的方法。
我后面看看能不能用其他方法替代

**Comment by Rosemoe** [comment]
0.11.1是否还有此问题？

**Comment by zhxzkhz** [comment]
> 

目前没有问题
