### ISSUE TITLE
How to enable the bottom toolbar and code error checking.

### ISSUE THREAD

**Issue by etjson** [Rosemoe/sora-editor#163]
How to enable the bottom toolbar and code error checking.

![image](https://user-images.githubusercontent.com/41315967/159402435-a25cb7cb-c649-4c56-9301-50214b0626cd.png)

**Comment by etjson** [comment]
如何开启底部的这个工具栏？在set方法里面没找到，不会需要自己画吧，还有代码的错误检查是怎么开启的，我配置了高亮并不包含。

**Comment by dingyi222666** [comment]
> 如何开启底部的这个工具栏？在set方法里面没找到，不会需要自己画吧，还有代码的错误检查是怎么开启的，我配置了高亮并不包含。

都是需要自己实现的 代码错误检查可以自己用parser手写错误检查 工具栏可以直接用recyclerview适配器来做

**Comment by dingyi222666** [comment]
> How to enable the bottom toolbar and code error checking.
> 
> ![image](https://user-images.githubusercontent.com/41315967/159402435-a25cb7cb-c649-4c56-9301-50214b0626cd.png)
> 

You need to implement your features by self. You can use lexer and parser to check code . The symbol toolbar can be implement with the recyclerview adapter

**Comment by Rosemoe** [comment]
符号输入用内置的SymbolInputView也行 
用法参见sample app

语法错误不自带 我这又不是IDE。
如需自己实现请查看language框架和MappedSpans.Builder#markProblemRegion方法

**Comment by etjson** [comment]
> 

好的，谢谢，我试下。
