### ISSUE TITLE
language-textmate 不兼容android 6.0

### ISSUE THREAD

**Issue by fengzhu2007** [Rosemoe/sora-editor#165]
IntFunction  forEach 这些都无法在使用 最低版本至少要24

**Comment by Rosemoe** [comment]
请自行查找coreLibDesugaring相关内容。你可以看看本项目app的build.gradle里面有什么。
通过解糖，这些可以在低版本Android使用。而且textmate只是从tm4e移植的，我不保证其在各Android版本上的兼容性。
