### ISSUE TITLE
ANR and crash issue when editor is in Wordwrap mode.

### ISSUE THREAD

**Issue by AmitBalani** [Rosemoe/sora-editor#168]
App goes in ANR when editor is placed in wordwrap mode.
Steps to produce ANR:-
1. Feature Switches -> Wordwrap On
2. go to end of sample code.
3. Type anything (make sure it should be more than 1 line)
4. Try to delete that line with holding backpress.
5. app will not respond and app get crashed after a while. i.e.:- It goes in ANR. (App Not Responding)

-- I have added a screenrecording for your reference, please check.

P.S.:- I tried to debug and find issue. I got error in EditorPainter file while calling getColumnCount() method.
i was not able to resolve it.
i hope you do it as soon as possible.
Regards.

https://user-images.githubusercontent.com/48736267/161495676-d3073cb7-5d46-4fbb-8015-2499c8d2ab4d.mp4

**Comment by Rosemoe** [comment]
I've reproduced this and I'll fix this recently

**Comment by Boss2410** [comment]
Hi @Rosemoe i also got this issue Any Fix for this ?
