### ISSUE TITLE
2nd character isn’t showing.

### ISSUE THREAD

**Issue by GourabSutradhar** [Rosemoe/sora-editor#171]
I am using editor module with language-java.When I write on it the 2nd character of each line isn’t  show.I am added a video for better understand.

https://user-images.githubusercontent.com/69720873/162664814-2410368f-166c-47f3-bccb-76f332099d36.mp4

**Comment by Rosemoe** [comment]
Are you using 0.10.11?

**Comment by GourabSutradhar** [comment]
No,I am using 0.10.10

**Comment by Rosemoe** [comment]
It's fixed in 0.10.11

**Comment by GourabSutradhar** [comment]
It is working😃.Thank you for making a such awesome editor🙂
