### ISSUE TITLE
Suggestion layout overlaps keyboard layout

### ISSUE THREAD

**Issue by GourabSutradhar** [Rosemoe/sora-editor#172]
The suggestion layout overlaps keyboard layout. Some characters cannot be written using the soft keyboard, it is very annoying. Please move the suggestion layout below the keyboard layout.
When I tried to wright `System.out.println();` I got the issue.
editor version 0.10.11

![Screenshot_2022-04-16-08-22-42-74_7ac4e00cb2f146b133349cab7b56dbc3](https://user-images.githubusercontent.com/69720873/163657957-4a982dd8-f63a-4610-bb92-3fa54cfc04dd.jpg)
![Screenshot_2022-04-15-11-31-42-01_7ac4e00cb2f146b133349cab7b56dbc3](https://user-images.githubusercontent.com/69720873/163657959-45125c78-5f5a-42da-9fa0-19229ff7853a.jpg)
![Screenshot_2022-04-15-11-31-28-91_7ac4e00cb2f146b133349cab7b56dbc3](https://user-images.githubusercontent.com/69720873/163657961-0ebabebd-0f1b-47c8-b5ca-91c91e2a9b9e.jpg)

**Comment by Rosemoe** [comment]
See #33 for more information. There is no solution to this by editor itself.

**Comment by Rosemoe** [comment]
The keyboard is a window inset which is not to be handled by editor. When your keyboard is shown, I can't get the exact invisible area caused by the keyboard.

**Comment by Arashvscode** [comment]
> The suggestion layout overlaps keyboard layout. Some characters cannot be written using the soft keyboard, it is very annoying. Please move the suggestion layout below the keyboard layout. When I tried to wright `System.out.println();` I got the issue. editor version 0.10.11
> 
> ![Screenshot_2022-04-16-08-22-42-74_7ac4e00cb2f146b133349cab7b56dbc3](https://user-images.githubusercontent.com/69720873/163657957-4a982dd8-f63a-4610-bb92-3fa54cfc04dd.jpg) ![Screenshot_2022-04-15-11-31-42-01_7ac4e00cb2f146b133349cab7b56dbc3](https://user-images.githubusercontent.com/69720873/163657959-45125c78-5f5a-42da-9fa0-19229ff7853a.jpg) ![Screenshot_2022-04-15-11-31-28-91_7ac4e00cb2f146b133349cab7b56dbc3](https://user-images.githubusercontent.com/69720873/163657961-0ebabebd-0f1b-47c8-b5ca-91c91e2a9b9e.jpg)

Used in code 
getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_VISIBLE|WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
editor.setLineNumberAlign(Paint.Align.CENTER);
