### ISSUE TITLE
Leaks

### ISSUE THREAD

**Issue by Arjuna91827** [Rosemoe/sora-editor#175]
```
┬───
│ GC Root: Thread object
│
├─ io.github.rosemoe.sora.lang.analysis.
│  AsyncIncrementalAnalyzeManager$LooperThread instance
│    Leaking: UNKNOWN
│    Retaining 865.5 kB in 12323 objects
│    Thread name: 'AsyncAnalyzer-4'
│    ↓ AsyncIncrementalAnalyzeManager$LooperThread.this$0
│                                                  ~~~~~~
├─ io.github.rosemoe.sora.langs.java.JavaIncrementalAnalyzeManager instance
│    Leaking: UNKNOWN
│    Retaining 855.4 kB in 12271 objects
│    ↓ AsyncIncrementalAnalyzeManager.receiver
│                                     ~~~~~~~~
├─ io.github.rosemoe.sora.widget.CodeEditor instance
│    Leaking: YES (View.mContext references a destroyed activity)
│    Retaining 849.5 kB in 12232 objects
│    View is part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mID = R.id.editor
│    View.mWindowAttachCount = 1
│    mContext instance of io.github.rosemoe.sora.app.MainActivity with
│    mDestroyed = true
│    ↓ View.mContext
╰→ io.github.rosemoe.sora.app.MainActivity instance
​     Leaking: YES (ObjectWatcher was watching this because io.github.rosemoe.
​     sora.app.MainActivity received Activity#onDestroy() callback and
​     Activity#mDestroyed is true)
​     Retaining 6.7 kB in 231 objects
​     key = 5c96bc3a-6074-4ff9-ba95-3f3b9192a646
​     watchDurationMillis = 7456
​     retainedDurationMillis = 2454
​     mApplication instance of android.app.Application
​     mBase instance of androidx.appcompat.view.ContextThemeWrapper

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Xiaomi
LeakCanary version: 2.9.1
App process name: io.github.rosemoe.sora.app
Class count: 11109
Instance count: 174948
Primitive array count: 127281
Object array count: 16692
Thread count: 22
Heap total bytes: 16361636
Bitmap count: 124
Bitmap total bytes: 2776576
Large bitmap count: 0
Large bitmap total bytes: 0
Db 1: open /data/user/0/io.github.rosemoe.sora.app/databases/leaks.db
Stats: LruCache[maxSize=3000,hits=36579,misses=88543,hitRate=29%]
RandomAccess[bytes=4571232,reads=88543,travel=27180411797,range=21441960,size=26
368602]
Analysis duration: 23133 ms```

**Comment by Rosemoe** [comment]
It's the same as #174

**Comment by Arjuna91827** [comment]
> It's the same as #174

Please solve this issue

**Comment by Arjuna91827** [comment]
Pl

> 

Please solve this issue

**Comment by Arjuna91827** [comment]
> ```
> ┬───
> │ GC Root: Thread object
> │
> ├─ io.github.rosemoe.sora.lang.analysis.
> │  AsyncIncrementalAnalyzeManager$LooperThread instance
> │    Leaking: UNKNOWN
> │    Retaining 865.5 kB in 12323 objects
> │    Thread name: 'AsyncAnalyzer-4'
> │    ↓ AsyncIncrementalAnalyzeManager$LooperThread.this$0
> │                                                  ~~~~~~
> ├─ io.github.rosemoe.sora.langs.java.JavaIncrementalAnalyzeManager instance
> │    Leaking: UNKNOWN
> │    Retaining 855.4 kB in 12271 objects
> │    ↓ AsyncIncrementalAnalyzeManager.receiver
> │                                     ~~~~~~~~
> ├─ io.github.rosemoe.sora.widget.CodeEditor instance
> │    Leaking: YES (View.mContext references a destroyed activity)
> │    Retaining 849.5 kB in 12232 objects
> │    View is part of a window view hierarchy
> │    View.mAttachInfo is null (view detached)
> │    View.mID = R.id.editor
> │    View.mWindowAttachCount = 1
> │    mContext instance of io.github.rosemoe.sora.app.MainActivity with
> │    mDestroyed = true
> │    ↓ View.mContext
> ╰→ io.github.rosemoe.sora.app.MainActivity instance
> ​     Leaking: YES (ObjectWatcher was watching this because io.github.rosemoe.
> ​     sora.app.MainActivity received Activity#onDestroy() callback and
> ​     Activity#mDestroyed is true)
> ​     Retaining 6.7 kB in 231 objects
> ​     key = 5c96bc3a-6074-4ff9-ba95-3f3b9192a646
> ​     watchDurationMillis = 7456
> ​     retainedDurationMillis = 2454
> ​     mApplication instance of android.app.Application
> ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper
> 
> METADATA
> 
> Build.VERSION.SDK_INT: 29
> Build.MANUFACTURER: Xiaomi
> LeakCanary version: 2.9.1
> App process name: io.github.rosemoe.sora.app
> Class count: 11109
> Instance count: 174948
> Primitive array count: 127281
> Object array count: 16692
> Thread count: 22
> Heap total bytes: 16361636
> Bitmap count: 124
> Bitmap total bytes: 2776576
> Large bitmap count: 0
> Large bitmap total bytes: 0
> Db 1: open /data/user/0/io.github.rosemoe.sora.app/databases/leaks.db
> Stats: LruCache[maxSize=3000,hits=36579,misses=88543,hitRate=29%]
> RandomAccess[bytes=4571232,reads=88543,travel=27180411797,range=21441960,size=26
> 368602]
> Analysis duration: 23133 ms```
> ```

Please solve this issue
