### ISSUE TITLE
Spans don't work properly with textmate

### ISSUE THREAD

**Issue by PranavPurwar** [Rosemoe/sora-editor#179]
![2022-05-15 12-27-40 High Res Screenshot](https://user-images.githubusercontent.com/75154889/168468569-ef6b3c05-6e91-4e2e-a8ad-bc789f40fbc3.png)
As you can see above, the text after 'import' keyword is being highlighted even tho it shouldn't do so.
I'm using TextMate language for java.
editor and textmate language modules are used from the latest commit 9ec9972
The syntax configuration is from the assets folder from this repository

**Comment by PranavPurwar** [comment]
same for the latest debug app build from github-actions of this repo 
![Screenshot_2022-05-15-16-17-58](https://user-images.githubusercontent.com/75154889/168469032-08b521a0-f5c7-4212-9611-13d80acb1b30.png)

**Comment by Arashvscode** [comment]
> same for the latest debug app build from github-actions of this repo ![Screenshot_2022-05-15-16-17-58](https://user-images.githubusercontent.com/75154889/168469032-08b521a0-f5c7-4212-9611-13d80acb1b30.png)
I texted the developer several times but he always said he could not fix the bug so use Java Server
textmeta is still experimental and incomplete

**Comment by Rosemoe** [comment]
Unfortunately, the bug is caused by the language file, which is not created by me. I have never looked into the textmate file yet. So I am unable to fix this.
