### ISSUE TITLE
EditorPopupWindow anchor besides content

### ISSUE THREAD

**Issue by rislaed** [Rosemoe/sora-editor#180]
Using library, I ran into the problem of not being able to use built-in ui components outside setContentView/Fragment window.

![screenshot_initial](https://user-images.githubusercontent.com/92180217/168484829-f0b922f8-60e4-472d-ba4c-7ee7ae5bebb5.png)
I'm using a WindowManager to display CodeEditor, but in that case, popups result in an instant error 'invalid window token' in built-in text selection component when clicking to appear it.

![screenshot_log](https://user-images.githubusercontent.com/92180217/168484850-9dba1912-a810-4f45-8504-6d7d2e8c843e.png)
Suggestion: built-in `EditorPopupWindow#setAnchor(View)`.

**Comment by Rosemoe** [comment]
I wonder how to display the editor by a WindowManager? A window floating above other applications?

**Comment by rislaed** [comment]
Just something like context.getSystemService('window').addView(content);

**Comment by Rosemoe** [comment]
Calling PopupWindow#setAnchor() seems not to help as I read the source code of PopupWindow. Have you tried that?

**Comment by Rosemoe** [comment]
Also, TextView's handle uses the same method to create its sub-window.

**Comment by rislaed** [comment]
Nope, that's not exactly what I meant.
I've must show component popup in decor, so method `EditorPopupWindow#setAnchor` must set parent where you want to display window. That is 'PopupWindow#showAtLocation (parent, gravity, x, y)', where parent is anchor which i meant.
Accordingly, in future I want to get necessary ui component and call on prototype EditorPopupWindow `setAnchor(View parent)` or something like that, which will set necessary parent for window.

**Comment by rislaed** [comment]
And in a window, accordingly, there cannot be one more sub-window, because it in itself is such.

**Comment by Rosemoe** [comment]
I see. But I still do not know why that exception is happening.

**Comment by MaXFeeD** [comment]
@Rosemoe Because it's happening. I really don't like working with popup windows on android '_'
