### ISSUE TITLE
How do you indicate errors/warnings

### ISSUE THREAD

**Issue by PranavPurwar** [Rosemoe/sora-editor#185]
According to the readme, i can see that it supports Error/Warning/Typo/Deprecated indicators.
Now my question is, how do i actually use this feature in my project.
I have a list of error/warnings with their position and line numbers.

**Comment by Rosemoe** [comment]
MappedSpans#markProblemRegion
or
MappedSpans.Builder#markProblemRegion
or
You can learn form CodeAssist

**Comment by PranavPurwar** [comment]
Thanks. Btw I actually earlier tried to see that in CodeAssist but it was just too difficult for me to find the actual place adding spans to the text due to its huge size of codebase
