### ISSUE TITLE
Code Suggestions in Textmate

### ISSUE THREAD

**Issue by m-anshuman2166** [Rosemoe/sora-editor#189]
Would like to see if it would be possible to add code suggestions in textmate

**Comment by PranavPurwar** [comment]
How do you manually add keywords to TextMate language tho? It seems that the current impl doesn't support adding keywords

**Comment by dingyi222666** [comment]
> How do you manually add keywords to TextMate language tho? It seems that the current impl doesn't support adding keywords


Modify the syntax file

**Comment by PranavPurwar** [comment]
Can you elaborate on **what** to modify in the syntax file? I tried using original grammers but it didn't show the keywords (im not talking about identifiers but language keywords)

**Comment by PranavPurwar** [comment]
Currently I can only handle it by modifying the TextMate language to add keywords in IdentifierAutoComplete

**Comment by dingyi222666** [comment]
> How do you manually add keywords to TextMate language tho? It seems that the current impl doesn't support adding keywords

Do you want to add keywords to the syntax highlight or to the auto-completion window?

**Comment by PranavPurwar** [comment]
to the auto completion window

**Comment by dingyi222666** [comment]
> to the auto completion window

Oh,That's easy.

See [this](https://gist.github.com/dingyi222666/efaac43a12781dc82abc83b5ffd342a6)
