### ISSUE TITLE
Highlight Matching Delimiters

### ISSUE THREAD

**Issue by massivemadness** [Rosemoe/sora-editor#194]
Highlight the opening or closing delimiter (`()`, `[]`, `{}`, and `<>`) like in desktop IDEA

<img width="336" alt="Снимок экрана 2022-06-14 в 16 36 05" src="https://user-images.githubusercontent.com/7825871/173590364-bf5a2b8b-d8e2-45a2-a5b8-ae0a1178f4ba.png">

I did this in my code editor as a plugin [BracketsHighlightPlugin.kt](https://github.com/massivemadness/Squircle-IDE/blob/master/editorkit/src/main/kotlin/com/blacksquircle/ui/editorkit/plugin/delimiters/BracketsHighlightPlugin.kt), but in sora editor it probably will be implemented in different way

**Comment by Rosemoe** [comment]
I think it's a good idea. In IDEA, the brackets matching is done based on PSI structure. According to my rough memory, VSC also has a brackets tree that is maintained dynamically to show brackets in the code...
However those are really professional. I will probably do similar things like yours while considering adding attributes to the span to indicate where the brackets should not be matched such as inner area of comments.

**Comment by PranavPurwar** [comment]
Would it be possible to perform this in textmate language with the bracket providers in language-configuration.json?

**Comment by Rosemoe** [comment]
> Would it be possible to perform this in textmate language with the bracket providers in language-configuration.json?

Actually not very realistic... Textmate doesn't give tokens
I would rather turn to the method composed by massivemadness.

**Comment by Rosemoe** [comment]
> Would it be possible to perform this in textmate language with the bracket providers in language-configuration.json?

Completed now.

**Comment by massivemadness** [comment]
> I will probably do similar things like yours while considering adding attributes to the span to indicate where the brackets should not be matched such as inner area of comments.

Just checked it, bracket highlighting works in the comment area 🤷‍♂️  
Is it possible to change the background color of highlighted brackets?

**Comment by Rosemoe** [comment]
> > I will probably do similar things like yours while considering adding attributes to the span to indicate where the brackets should not be matched such as inner area of comments.
> 
> Just checked it, bracket highlighting works in the comment area 🤷‍♂️ Is it possible to change the background color of highlighted brackets?

In Java language, it will not work in comments.
Background is not yet added.
