### ISSUE TITLE
Gboard related issue

### ISSUE THREAD

**Issue by Raival-e** [Rosemoe/sora-editor#200]
Hi,
I've noticed that using Gboard with suggestions enabled causes an issue as shown in the video:

https://user-images.githubusercontent.com/81700082/174603497-cf78b138-962f-4dce-a5e7-9ab5c1ce5518.mp4

**Comment by Rosemoe** [comment]
Hi, thanks for your feedback. Actually the problem is reported informally before.  And I'm still researching why it is happenning. I'll try to fix it.

**Comment by Rosemoe** [comment]
> Not sure if this was fixed in 0.15.0 but i no more face it 😅

It still exists
