### ISSUE TITLE
Issues after updating to v0.13.0

### ISSUE THREAD

**Issue by PranavPurwar** [Rosemoe/sora-editor#209]
After updating the library to v0.13.0 the editor has stopped working properly. Sometimes it types the text 2 times or deletes new lines

https://user-images.githubusercontent.com/75154889/175808627-6ef4bde0-8db3-4bab-87fb-38919d38ac8d.mp4

**Comment by Rosemoe** [comment]
What keyboard are you using?

**Comment by PranavPurwar** [comment]
It's xiaomi's built in keyboard i don't really know the correct name. But one thing I can say is that it was working in older versions
