### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by Raival-e** [Rosemoe/sora-editor#212]
Hi,
In some occasions (like the one shown in the video below), I can't scroll to the end of the line.

https://user-images.githubusercontent.com/81700082/175907110-2cfd03f1-90a0-49b7-8736-c07bc6469ead.mp4

**Comment by Rosemoe** [comment]
Is there anything special happened before?
Is there a way to reproduce it 100%?
Thanks

**Comment by Rosemoe** [comment]
Ok. I successfully reproduced it. I'll check why it is happening.
