### ISSUE TITLE
Add diagnostics message for lines

### ISSUE THREAD

**Issue by radimitrov** [Rosemoe/sora-editor#217]
Correct me if I'm wrong but right now editor diagnostics are purely cosmetic. I couldn't find a way to add an error message. Could you add that as a feature? Would be really useful.
Just to clarify not automated language error checking, just the ability to add a string there that can be showed on click.
Clicking the warning symbol in the second line should show a popup/overlay message, which in this case would be something like "unused variable a". Clicking the error on line 3 would show for example "PriNtLn is undefined". 

Here is a quick visualization:

1 ---| public static void main(String[] args) {
2⚠| int a = 0;
3❌|System.out.PriNtLn();
4 ---| }

**Comment by itsaky** [comment]
@radimitrov It's pretty easy to implement.

Refer [DiagnosticWindow](https://github.com/itsaky/AndroidIDE/blob/main/app/src/main/java/com/itsaky/androidide/views/editor/DiagnosticWindow.java) and [BaseEditorWindow](https://github.com/itsaky/AndroidIDE/blob/main/app/src/main/java/com/itsaky/androidide/views/editor/BaseEditorWindow.java) to see how the window has been implemented. The window classes do not use any of the AndroidIDE APIs except the [DiagnosticItem](https://github.com/itsaky/AndroidIDE/blob/846f81efccaff4d36e9c0e8da7a27f3bb6cde9ad/lsp/api/src/main/java/com/itsaky/lsp/models/Diagnostics.kt#L32) model. So it should be simple to understand.

[This](https://github.com/itsaky/AndroidIDE/blob/846f81efccaff4d36e9c0e8da7a27f3bb6cde9ad/app/src/main/java/com/itsaky/androidide/views/editor/IDEEditor.java#L110) is how the window is shown.

**Comment by radimitrov** [comment]
Yes, the DiagnosticWindow part is easy. At least that way via the cursor position. Thanks for the example.
But wouldn't this result in frequent accidental showing of the window when you just click somewhere?

On the other hand adding clickable boxes in the lines column will require changes to the renderer.
Though that also falls under the IDE category and there is also an easy way I can to that with a small change.

You can close this issue, I think. 
Sorry for late reply.

**Comment by itsaky** [comment]
> But wouldn't this result in frequent accidental showing of the window when you just click somewhere?

That window contains only a single-line text view. So it doesn't occupy a lot of space. Also, it can be hidden by selecting another position.

Anyways, you could always show the window on a `LongClickEvent`.

**Comment by radimitrov** [comment]
I will need to modify the window to contain a lot more than 1 line.
And that's the the basic idea I've got too - ClickEvent with x checks for the lines column to limit showing the diagnostics.
