### ISSUE TITLE
Brackets matching line for HTML or Custom characters

### ISSUE THREAD

**Issue by AndroXStudiO** [Rosemoe/sora-editor#219]
Add Brackets matching line  for  also HTML or Custom characters

Its working for only java codes that contain "{ }"

But i shoulder work for HTML also.
e.g.
"<>  </>"

**Comment by AndroXStudiO** [comment]
![Uploading images (9).jpeg…]()

**Comment by AndroXStudiO** [comment]
![Uploading images (9).jpeg…]()

**Comment by Rosemoe** [comment]
Your image hasn't been uploaded...?
I can not view it...

**Comment by AndroXStudiO** [comment]
![Uploading images (9).jpeg…]()

**Comment by AndroXStudiO** [comment]
> Your image hasn't been uploaded...? I can not view it...

Sorry for that issue. 

Actually this image as preview of Brackets matching line for HTML.  As known as, sora-editor  is the best editor for android. Its very smooth and fast. But its not support "Brackets matching line" for HTML codes.

**Comment by Rosemoe** [comment]
> > Your image hasn't been uploaded...? I can not view it...
> 
> Sorry for that issue.
> 
> Actually this image as preview of Brackets matching line for HTML. As known as, sora-editor is the best editor for android. Its very smooth and fast. But its not support "Brackets matching line" for HTML codes.

Could you send a preview image in the telegram group?

**Comment by AndroXStudiO** [comment]
Yes....sure send me join link

**Comment by Rosemoe** [comment]
https://t.me/rosemoe_code_editor

**Comment by AndroXStudiO** [comment]
Not yet. I am trying from 2day with TextMate on Sketchware pro

**Comment by BlueWhaleYT** [comment]
The availability of line separator for HTML language depends on its `language-configuration.json` file.
