### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by you814455** [Rosemoe/sora-editor#225]
drawRows 能优化下吗，花费内存较大

**Comment by Rosemoe** [comment]
请带上详细日志

**Comment by Rosemoe** [comment]
你看到的是否形如以下日志：
Compiler allocated xMB to compile void io.github.rosemoe.widget.EditorPainter.drawRows(...

**Comment by you814455** [comment]
> 



> 你看到的是否形如以下日志： Compiler allocated xMB to compile void io.github.rosemoe.widget.EditorPainter.drawRows(...

对，也有gc回收

**Comment by Rosemoe** [comment]
compiler提示只是因为：1.方法使用频繁，进行编译
2.方法逻辑较复杂，编译时耗费了内存
并不是方法执行时创建了很多对象或者大的对象。

android.view.ViewRootImpl#performTraversals,TextView#init也有类似提示。AOSP改了我就改。
