### ISSUE TITLE
Wrong line separator 

### ISSUE THREAD

**Issue by AndroXStudiO** [Rosemoe/sora-editor#226]
I am using TextMate.

![Screenshot_2022-07-18-08-59-09-51_83ef8e9c9b682a1b3e35f92d1926ce29](https://user-images.githubusercontent.com/88816748/179439769-11d339d4-a328-49d4-9220-d93f8367693f.jpg)

**Comment by AndroXStudiO** [comment]
![IMG_20220718_091015](https://user-images.githubusercontent.com/88816748/179439911-04f8a2a3-fa2a-4beb-9058-0b05811e8e1c.jpg)

**Comment by Rosemoe** [comment]
Well, it's just correct in textmate.
Because textmate uses 'indent' to compute the folding regions.

If you would like to make it better, you may need to use a custom parser to analyze the start and end of Xml tags.

**Comment by AndroXStudiO** [comment]
Where i can change indent?  Or Custom parse?

**Comment by Rosemoe** [comment]
> Where i can change indent?  Or Custom parse?

Override the _computeBlocks_ method in TextmateAnalyzer to customize your own code block computing logic.
But if you use a custom parser, you may prefer to use AsyncAnalyzeManager directly to maximize the benefits of your parser.
