### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by you814455** [Rosemoe/sora-editor#236]
不是支持绘制错误线吗，怎么没有方法调用

**Comment by Rosemoe** [comment]
![image](https://user-images.githubusercontent.com/28822819/187866244-df44db9d-470e-4f52-b7d6-b4f1957f42f5.png)

**Comment by Rosemoe** [comment]
![image](https://user-images.githubusercontent.com/28822819/187866825-622fb5f3-17a0-44f3-a7c0-9e4f341b2ecb.png)

**Comment by you814455** [comment]
旧版本没有吗，旧的StyleReceiver只有setStyles

**Comment by Rosemoe** [comment]
旧的版本直接挂在Span上，problemFlags
