### ISSUE TITLE
Double-click selection issue

### ISSUE THREAD

**Issue by Raival-e** [Rosemoe/sora-editor#238]
Hi,
I'm not sure if this is an intended behaviour or not, but I find it almost impossible to select a single symbol character (e.g. `"`, `;`, `)`...etc) in specific situations as demonstrated in the video below. 

When I double tap on a character, it usually ends up selecting the character/word before/after it. At first, I thought it was my fault that I don't click the exact position of the character due to the small font size, but I struggled even after I zoom in, and I don't encounter this issue in the ordinary EditText. 

You can see in the video that I couldn't select the opening parenthesis `(` at all, but that wasn't the case for the closing one `)`, same for the semicolon in `m;`.

https://user-images.githubusercontent.com/81700082/187888713-b1899303-124e-48f3-967c-082a6465335e.mp4

**Comment by Rosemoe** [comment]
Well, try to set `DirectAccessProps.useICULibToSelectWords` to `false` and retry.
I think this can be caused by the system library because it works on my Redmi K50 and Xiaomi 9 device.

**Comment by Raival-e** [comment]
It is false, switching it to true seems to fix the issue though

**Comment by Raival-e** [comment]
Hi, 
This bug still exists
