### ISSUE TITLE
Editor freezing

### ISSUE THREAD

**Issue by PranavPurwar** [Rosemoe/sora-editor#245]
In our application, we show the CodeEditor fragment inside a ViewPager2. But it seems like its causing some issues with Editor, causing it to suddenly start freezing randomly. Here's a video of that happening: https://youtube.com/shorts/W3KhGIvwKh0?feature=share

Any help would be appreciated.

**Comment by Rosemoe** [comment]
Any logs related to `EditorInputConnection` and `IInputConnectionWrapper`? Send them to me please.
And if possible, set the DEBUG flag to true by reflecting when collecting these logs.
![image](https://user-images.githubusercontent.com/28822819/188807050-6f65af34-6a3a-41aa-836d-a191d37ccad0.png)

**Comment by PranavPurwar** [comment]
Here are the logs we could gather from those classes
![Screenshot_2022-09-07-14-55-58-101_com pluscubed matlog](https://user-images.githubusercontent.com/75154889/188840696-b30cf4ea-f5ff-4503-9e4f-ac8ba9139b06.jpg)
![IMG_20220907_145717](https://user-images.githubusercontent.com/75154889/188840727-57b0a7b1-c2f4-4c96-b611-e82f6b5616f8.jpg)

**Comment by PranavPurwar** [comment]
Seems like it was an issue with a custom ContentListener used in the project, still not sure why it only started freezing after the update.

**Comment by Rosemoe** [comment]
Did you solve the problem after removing that ContentListener?

**Comment by PranavPurwar** [comment]
Nope, I was using Application context for loading a SharedPreferences. I think the editor should catch Exceptions from ContentListener and not just freeze because of that

**Comment by Rosemoe** [comment]
But well, how should we present these exceptions (to user) after catching them? We can't swallow the exceptions without any notification. Log is not enough I think.

For example, JetBrains IDEs will show a message balloon for IDE errors. But editor is a standalone library, not an integrated IDE component.

**Comment by PranavPurwar** [comment]
I don't think users would need to see exception logs, isn't this thing meant to be tested well by the developers, first?

**Comment by Rosemoe** [comment]
A CrashHandler like the one in sample app would be fine
