### ISSUE TITLE
matching delemeter line is inaccurate when using tabs

### ISSUE THREAD

**Issue by PranavPurwar** [Rosemoe/sora-editor#248]
It seems like the editor doesn't properly show the delimeter line when we use tabs instead of spaces in code 
![Screenshot_2022-09-11-20-39-34-612_org cosmic ide debug](https://user-images.githubusercontent.com/75154889/189535274-b3177f64-14b6-4fe5-b02e-950b1805b887.jpg)

**Comment by Rosemoe** [comment]
I think it is not releated to tabs because in sample app it works

**Comment by Rosemoe** [comment]
Which app? Could you send it?

**Comment by PranavPurwar** [comment]
this one https://github.com/Raival-e/File-Explorer

**Comment by Rosemoe** [comment]
Ok thanks. I'll check it later

**Comment by Rosemoe** [comment]
Well is there any way to reproduce it?
I downloaded an apk from releases v1.0.0 and created a file with Java code template, but it isn't happening.

**Comment by BanDroid** [comment]
Mine does too

![Screenshot_2022-09-11-16-37-54-305_org.cosmic.ide.debug.jpg](https://user-images.githubusercontent.com/68449470/189873850-02e028df-7df3-4e8d-88e3-513bcecf3336.jpg)

**Comment by Raival-e** [comment]
It has something to do with TextMate language, I tried in the [latest debug build](https://github.com/Rosemoe/sora-editor/actions/runs/3043498504) and I can confirm that it does exist.

To reproduce, change the editor language to `Textmate Kotlin`, then remove the old code and paste this:
[bug.txt](https://github.com/Rosemoe/sora-editor/files/9556296/bug.txt)

**Comment by Raival-e** [comment]
btw, It only occurs when using tabs instead of spaces as @PranavPurwar stated.

**Comment by Rosemoe** [comment]
It does exist. I reproduced successfully. I'll check why this is happening.
