### ISSUE TITLE
Support custom scrollbar thumb and track

### ISSUE THREAD

**Issue by MuntashirAkon** [Rosemoe/sora-editor#250]
CodeEditor should support the Android-default scrollbar properties, namely `android:scrollbarTrackHorizontal`, `android:scrollbarTrackVertical`, `android:scrollbarThumbHorizontal` and `android:scrollbarThumbVertical`. These aren't currently supported because the library draws custom rectangle in the `EditorRenderer` class. Setting custom thumb and track for the scrollbars allows a developer to maintain consistency across the application.

Currently, the API is flexible enough to allow a developer to draw custom shapes or bitmap images. The example below allows me to maintain consistency by drawing a rounded thumb and a rounded track:

<details>
  <summary>CustomEditorRenderer.java</summary>

```java
public class CustomEditorRenderer extends EditorRenderer {
    private final CodeEditor editor;
    private final RectF tmpRect;
    private final RectF verticalScrollBarRect;
    private final RectF horizontalScrollBarRect;
    private final float cornerSize;

    public CustomEditorRenderer(@NonNull CodeEditor editor) {
        super(editor);
        this.editor = editor;
        tmpRect = new RectF();
        verticalScrollBarRect = new RectF();
        horizontalScrollBarRect = new RectF();
        cornerSize = editor.getDpUnit() * 8;
    }

    protected void drawRoundedRectangle(Canvas canvas, int color, RectF rect) {
        if (color != 0) {
            paintGeneral.setColor(color);
            canvas.drawRoundRect(rect, cornerSize, cornerSize, paintGeneral);
        }
    }

    @Override
    public RectF getVerticalScrollBarRect() {
        return verticalScrollBarRect;
    }

    @Override
    public RectF getHorizontalScrollBarRect() {
        return horizontalScrollBarRect;
    }

    @Override
    protected void drawScrollBars(Canvas canvas) {
        verticalScrollBarRect.setEmpty();
        horizontalScrollBarRect.setEmpty();
        super.drawScrollBars(canvas);
    }

    @Override
    protected void drawScrollBarTrackVertical(Canvas canvas) {
        if (editor.getEventHandler().holdVerticalScrollBar()) {
            tmpRect.right = editor.getWidth();
            tmpRect.left = editor.getWidth() - editor.getDpUnit() * 10;
            tmpRect.top = 0;
            tmpRect.bottom = editor.getHeight();
            drawRoundedRectangle(canvas, editor.getColorScheme().getColor(EditorColorScheme.SCROLL_BAR_TRACK), tmpRect);
        }
    }

    @Override
    protected void drawScrollBarVertical(Canvas canvas) {
        int height = editor.getHeight();
        float all = editor.getLayout().getLayoutHeight() + height / 2f;
        float length = height / all * height;
        float topY;
        if (length < editor.getDpUnit() * 60) {
            length = editor.getDpUnit() * 60;
            topY = (editor.getOffsetY()) / all * (height - length);
        } else {
            topY = editor.getOffsetY() / all * height;
        }
        if (editor.getEventHandler().holdVerticalScrollBar()) {
            float centerY = topY + length / 2f;
            drawLineInfoPanel(canvas, centerY, tmpRect.left - editor.getDpUnit() * 5);
        }
        tmpRect.right = editor.getWidth();
        tmpRect.left = editor.getWidth() - editor.getDpUnit() * 13;
        tmpRect.top = topY;
        tmpRect.bottom = topY + length;
        verticalScrollBarRect.set(tmpRect);
        drawRoundedRectangle(canvas, editor.getColorScheme().getColor(editor.getEventHandler().holdVerticalScrollBar()
                ? EditorColorScheme.SCROLL_BAR_THUMB_PRESSED
                : EditorColorScheme.SCROLL_BAR_THUMB), tmpRect);
    }

    @Override
    protected void drawScrollBarTrackHorizontal(Canvas canvas) {
        if (editor.getEventHandler().holdHorizontalScrollBar()) {
            tmpRect.top = editor.getHeight() - editor.getDpUnit() * 10;
            tmpRect.bottom = editor.getHeight();
            tmpRect.right = editor.getWidth();
            tmpRect.left = 0;
            drawRoundedRectangle(canvas, editor.getColorScheme().getColor(EditorColorScheme.SCROLL_BAR_TRACK), tmpRect);
        }
    }

    @Override
    protected void drawScrollBarHorizontal(Canvas canvas) {
        int page = editor.getWidth();
        float all = editor.getScrollMaxX();
        float length = page / (all + editor.getWidth()) * editor.getWidth();
        float leftX = editor.getOffsetX() / all * (editor.getWidth() - length);
        tmpRect.top = editor.getHeight() - editor.getDpUnit() * 10;
        tmpRect.bottom = editor.getHeight();
        tmpRect.right = leftX + length;
        tmpRect.left = leftX;
        horizontalScrollBarRect.set(tmpRect);
        drawRoundedRectangle(canvas, editor.getColorScheme().getColor(editor.getEventHandler().holdHorizontalScrollBar() ? EditorColorScheme.SCROLL_BAR_THUMB_PRESSED : EditorColorScheme.SCROLL_BAR_THUMB), tmpRect);
    }
}
```
</details>

But I believe this could be further improved by supporting the Android-default properties or by simplifying the API so that the rectangles can be drawn without much copy-and-paste job that I've done here.

**Comment by Rosemoe** [comment]
Well, I can't get the Android-default scrollbars to work... But I may use those Drawables. Do you think it's acceptable?

**Comment by MuntashirAkon** [comment]
> Well, I can't get the Android-default scrollbars to work... But I may use those Drawables. Do you think it's acceptable?

The default scrollbars shrink to an unusable level if the scrolling content is very large. So, you should be glad that they didn't work in first place :). But yes, it might be possible to use the drawables with canvas. I think the current API is very neat, all you have to do is use those drawables if set by the user.

**Comment by Rosemoe** [comment]
Ok I'll do it later.

**Comment by MuntashirAkon** [comment]
Take your time. I think scrolling is one of the biggest issues in Android UI development. So, a proper planning might be required at one point.

**Comment by Rosemoe** [comment]
Well, it's not very applicable because these getters are added on high API Android.
![image](https://user-images.githubusercontent.com/28822819/189854614-d222992c-dd24-4f71-9c74-50554f4b7032.png)

**Comment by Rosemoe** [comment]
We may need to add custom APIs to achieve the goal

**Comment by MuntashirAkon** [comment]
The API was there but the getters were added later. The best way to handle them is to declare them in the styleable file and fetch them using typedarray.

**Comment by MuntashirAkon** [comment]
I can help you with that if you're not familiar with styleables.

**Comment by Rosemoe** [comment]
I know a little about styleables but I have not add them to editor. And custom styleables are used like 'app:xxx' right?

**Comment by Rosemoe** [comment]
I'll appreciate it if you could help me. I do not have much time on weekdays.

**Comment by MuntashirAkon** [comment]
> custom styleables are used like 'app:xxx' right?

Yes. But in this particular case, you don't need to define any custom styleable.

> I'll appreciate it if you could help me. I do not have much time on weekdays.

OK, I don't exactly know what you're planning. But I would add 4 more variables in the CodeEditor which would store the drawables for vertical and horizontal tracks and thumbs, and open a PR. Then you can either specify your requirements or go on to implement the rests yourself.

**Comment by Rosemoe** [comment]
Ok, thanks!
