### ISSUE TITLE
ClassCastException on EditorTextActionWindow

### ISSUE THREAD

**Issue by tyron12233** [Rosemoe/sora-editor#261]
~~When the editor view is inflated from the default context constructor (`CodeEditor#<init>(Context)`) and a material themed context is passed to it, the material layout inflater changes the `android.widget.ImageButton` into its material variant which causes a ClassCastException.~~

Turns out it also occurs when using the default themed context.

Stacktrace: https://pastebin.com/QeRu1mTt

**Comment by tyron12233** [comment]
It may be an incremental recompilation issue on android studio, ill delete the resource cache and retry again.

**Comment by tyron12233** [comment]
It was an issue with the build system.

**Comment by rifas9037** [comment]
@tyron12233 Hi
