### ISSUE TITLE
Request: Replace kotlin files with java files

### ISSUE THREAD

**Issue by MohammedKHC** [Rosemoe/sora-editor#269]
Please replace kotlin files with java files because some peoples don't want to include the full kotlin library on their projects. and don't use it, kotlin library makes the project size bigger and slow down build progress on big projects There is really no point in using it in this library because only 7% from this library contains kotlin code.

**Comment by Rosemoe** [comment]
Well, personally I'm not to do that and we may add more Kotlin stuff in future.

**Comment by MohammedKHC** [comment]
@Rosemoe do you remember this?
This was back when I was DUMB.

NOW I HATE JAVA

TEAM KOTLIN!!

(also sorry for the ping, but man this is just funny)

Have a nice day!
