### ISSUE TITLE
There is white line on the cursor drawable

### ISSUE THREAD

**Issue by MohammedKHC** [Rosemoe/sora-editor#270]
A Photo explains what i mean:
![IMG_٢٠٢٢١٠١٩_٠٠٢١٣٦](https://user-images.githubusercontent.com/94754398/196556320-998db6b6-f47a-4ff5-b8ef-020c78a49a8f.jpg)

**Comment by Rosemoe** [comment]
Well, I'm unable to reproduce this. Is this happenning always or after any specific action?

**Comment by MohammedKHC** [comment]
This is happening always

**Comment by tegajoel** [comment]
I was able to reproduce this, and I created a PR that resolves this https://github.com/Rosemoe/sora-editor/pull/312
