### ISSUE TITLE
Add Feature to use multiple/custom colors

### ISSUE THREAD

**Issue by datechies** [Rosemoe/sora-editor#279]
Add Feature to use multiple/custom colors please

**Comment by Rosemoe** [comment]
You can set apply custom EditorColorScheme by CodeEditor#setColorScheme.
Also you are able to change the colors by updating the EditorColorScheme instance used by editor.
See also: CodeEditor#getColorScheme, EditorColorScheme#setColor and the static final fields of EditorColorScheme.

**Comment by Rosemoe** [comment]
You can use your custom color ids as long as there is not conflict with built-in ones.
See EditorColorScheme#END_COLOR_ID

**Comment by datechies** [comment]
😃😃😃
