### ISSUE TITLE
Seemingly can't add language with scope not "source"

### ISSUE THREAD

**Issue by JavkhlanK** [Rosemoe/sora-editor#288]
Hi, before telling my issue, I have no idea about TextMate and probably am just hacking things together so that it works. Now to the issue.

While trying to upgrade to v0.18.1, I wanted to use the new language and theme loading style. The app uses a TextMate language definition with scope `text.xml`, and trying to load it fails. Sora-editor apparently overwrites the set scope, and defaults to `source.$languageName`.

Here's some code trying to load the language file, and also debugging the scopes throughout the process:  
![Screenshot from 2022-11-08 09-04-40](https://user-images.githubusercontent.com/40118124/200508647-4486ff18-305f-4484-a01a-c4549b001581.png)

**Comment by dingyi222666** [comment]
See [here](https://github.com/Rosemoe/sora-editor/blob/main/language-textmate/src/main/java/io/github/rosemoe/sora/langs/textmate/registry/dsl/GrammarDefinitionDSL.kt#L69).

You can customize the prefix, or set the `scopeName` directly.

**Comment by dingyi222666** [comment]
I will fix it later.
