### ISSUE TITLE
I am using Gson 8.9.x, conflicting with sora-editor's Gson 9.1.x.

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Rosemoe/sora-editor#296]
The gson is used in textmate. Can it be possible to remove gson or to provide interface so that I can customize json parser?

**Comment by dingyi222666** [comment]
You can excluding a transitive dependency when introducing the sora-editor library, for more information see [here](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps)
