### ISSUE TITLE
[Question] Can I fix LineHeight and let layout_height="wrap_content"?

### ISSUE THREAD

**Issue by LinXueyuanStdio** [Rosemoe/sora-editor#297]
I want to create a code block in recyclerview. Code block is a type of block in markdown.

But CodeEditor embedded in ViewHolder must have a fixed layout_height. I wonder if the layout_height could change as the user writing lines of code.

I read the docs and code. It seems that CodeEditor should be a fixed layout. Is it right?
Do you have any idea to implement code block in recyclerview?

**Comment by Rosemoe** [comment]
It's not currently supported. If you do need it, I may improve measurements when I am free.

**Comment by devarsh-mavani-19** [comment]
@LinXueyuanStdio temporary solution is to set the layout params and set the width as original previous width and height as rowheight * linecount
