### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by kyze8439690** [Rosemoe/sora-editor#302]
Leaks in memory profile hprof:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/1637169/204142420-dcb079a7-dc9b-4d9a-bd91-d88521f747c7.png">

Use mapping to retrace classes:
```
io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager$LooperThread -> vd.b$d:
    io.github.rosemoe.sora.lang.analysis.AsyncIncrementalAnalyzeManager this$0 -> X
    ...
```

Maybe some long running task which failed to be canceled when destroying activity?

**Comment by Rosemoe** [comment]
`CodeEditor#release` is expected to be invoked by user when an editor instance is no longer used. When the activity is to be destroyed, you are expected to do so as well.
If you did call release() on destroy, I'll check whether it's caused by editor failure in ending the threads.

**Comment by kyze8439690** [comment]
I do not call `release()` when exit, thx for the tip.
