### ISSUE TITLE
License clarification/issue

### ISSUE THREAD

**Issue by radimitrov** [Rosemoe/sora-editor#306]
I'm interpreting the license text in contradicting ways so I could be understanding this wrong, but generally LGPL license mandates that one of these options is fullfulled along with copy of license and link to repository:
1. Share code of entire application if library is modified
2. Share only code of any modifications to the library (sora-editor) as a library and link it dynamically in the application.

However option 1 isn't applicable for my case. And I need to make modifications to be able to use this effectively. 
Unfortunetelly, I think option 2 is invalid for Android since I don't think there is a way to dedicate a classesN.dex just to the editor library to cover that part of the license.

Also under section 2c, it is unclear if "whole of the work" encloses the entire application or just the library. If it is application, then that is another issue that mandates sharing of application source.

Can this editor library be modified and used in a closed source commercial project by open sourcing just the modified library?

**Comment by Rosemoe** [comment]
Hi. Thanks for contacting.
I think just disclose the modified library under LGPL is fine. You do not have to make your whole application open-source. Besides, you may need to add some information (such as copyright) of this library in your application.

**Comment by radimitrov** [comment]
Thanks for the reply!
That's what I initially thought, but then I strarted reading the actual file.
I'll add your license the application's assets and about page.

**Comment by Rosemoe** [comment]
Thanks for your support and understanding!
