### ISSUE TITLE
Questions related to version 0.8.4

### ISSUE THREAD

**Issue by Arashvscode** [Rosemoe/sora-editor#309]
Hello, I am using version 0.8.4 because I don't want to lose the languages ​​I have produced, I just have a small question, how to implement the Google update Symbol in this version, it needs a special code, I mean the Symbol of these Symbols -> ===

**Comment by Rosemoe** [comment]
Use JetBrainsMono font

**Comment by Arashvscode** [comment]
> Use JetBrainsMono font

Similarly, something special is not needed?

**Comment by Rosemoe** [comment]
Yes. Those symbol appearances are just controlled by font.

**Comment by MohammedKHC** [comment]
> > Yes. Those symbol appearances are just controlled by font.
> 
> In fact, I have been using this font for 6 months, and now I downloaded it again and installed it on my project, but nothing has changed.

I think the problem is in your editor language, try set language to default and see if it works
