### ISSUE TITLE
Text disappeared after switch color scheme

### ISSUE THREAD

**Issue by SurendraSandun** [Rosemoe/sora-editor#316]
On my device editor text disappeared after I switch color scheme.
Device: Samsung Galaxy M21. Android 12 (One UI 4.1)
Before switch color scheme:
![Screenshot_20221220-183331_Sora-editor Demo](https://user-images.githubusercontent.com/39802449/208675255-589dfcb9-9066-4b8a-9f12-cadd1c688b5d.jpg)

After switch color sheme:
![Screenshot_20221220-183343_Sora-editor Demo](https://user-images.githubusercontent.com/39802449/208675803-e16f214d-6dce-4f9e-8092-fd7aadcb2dc4.jpg)
(Dracula Color Scheme)

Following themes make text disappeare:
Default, GitHub, Eclipse, Dracula, VS 2019, NotepadX.

Other Themes are work.

**Comment by Rosemoe** [comment]
Textmate language must use Textmate themes. Normal themes can not handle textmate color symbols.
