### ISSUE TITLE
Kindly add java implementation for editor-lsp module

### ISSUE THREAD

**Issue by sue-ivy** [Rosemoe/sora-editor#354]
I don't know anything about kotlin incase I used AndroidIDE to develop an app and it doesn't support kotlin yet (same as other ide) so it's hard to learn kotlin stuff without such as features like auto-completion/warning/etc...

In the demo app you guys used kotlin so here's some point that I don't get it
[this](https://github.com/Rosemoe/sora-editor/blob/main/app/src/main/java/io/github/rosemoe/sora/app/LspTestActivity.kt#L161) I don't understand how did you put those event stuff into a server definition's constructor? 

and [this](https://github.com/Rosemoe/sora-editor/blob/main/app/src/main/java/io/github/rosemoe/sora/app/LspTestActivity.kt#L294)
seems kinda interface but when I try to implement/extends that doesn't work as expected 

I also tried to implement textmate's new API things by converting smali to java, somehow I made it work but the lsp things doesn't convert well due to kotlin concurrent stuff I guess

Please, used java for the demo app if it's ok for you guys. I don't think java might be a problem for kotlin dev but for java dev who doesn't know anything about kotlin is a big thing...

**Comment by PranavPurwar** [comment]
> I don't know anything about kotlin incase I used AndroidIDE to develop an app and it doesn't support kotlin yet (same as other ide) so it's hard to learn kotlin stuff without such as features like auto-completion/warning/etc...
> 
> In the demo app you guys used kotlin so here's some point that I don't get it [this](https://github.com/Rosemoe/sora-editor/blob/main/app/src/main/java/io/github/rosemoe/sora/app/LspTestActivity.kt#L161) I don't understand how did you put those event stuff into a server definition's constructor?
> 
> and [this](https://github.com/Rosemoe/sora-editor/blob/main/app/src/main/java/io/github/rosemoe/sora/app/LspTestActivity.kt#L294) seems kinda interface but when I try to implement/extends that doesn't work as expected
> 
> I also tried to implement textmate's new API things by converting smali to java, somehow I made it work but the lsp things doesn't convert well due to kotlin concurrent stuff I guess
> 
> Please, used java for the demo app if it's ok for you guys. I don't think java might be a problem for kotlin dev but for java dev who doesn't know anything about kotlin is a big thing...

you could use codeassist for kotlin code completion

**Comment by Rosemoe** [comment]
Refer to demo app's LspTestJavaActivity
