### ISSUE TITLE
Docs for textmate bundles

### ISSUE THREAD

**Issue by MaxPleaner** [Rosemoe/sora-editor#355]
Hi, the docs here are not very clear or accessible.  I found these docs on your blog https://rosemoe.github.io/2021/08/22/editor-get-started/ but it's not linked from the README and I don't know if it's up to date. 

There are no docs for how to use textmate language bundles. 

I think the community would appreciate having better docs here.

**Comment by MaxPleaner** [comment]
Update, I just noticed that docs are in the individual folders. This is good to know, but I advise that you mention this on the README because it's very easy to miss it.

**Comment by MaxPleaner** [comment]
Ok, looking at the textmate docs again. There is no instructions for how to support a custom language (in my case GLSL)

**Comment by Rosemoe** [comment]
Actually, textmate is not originally designed by vscode or eclipse.
You may find more about the textmate language grammars [here](https://macromates.com/manual/en/language_grammars#example_grammar).
However, we (and also vscode&tm4e) use JSON or Property List to represent the language.

**Comment by MaxPleaner** [comment]
hi @Rosemoe , really what i am asking is if you can provide a code example for how to get syntax highlighting in Sora for any language besides Java. I am not looking to create custom grammars; I think most likely these already exist for all popular languahes. I looked at the code for a little while and I couldnt figure it out. There is also no example anywhere on your docs.
