### ISSUE TITLE
Text selection sometimes scrolls when it should move the selection

### ISSUE THREAD

**Issue by radimitrov** [Rosemoe/sora-editor#358]
It is most apparent at the start of the video. I'm dragging exactly at the end of the selection but the editor scrolls instead of changing the selection.

https://user-images.githubusercontent.com/56889141/212875420-dbf4e968-5d19-4901-be56-3d1c8ed2766a.mp4

**Comment by Rosemoe** [comment]
Your thumb didn't actually catch the selection handle. See this key frame I captured from your video:
![image](https://user-images.githubusercontent.com/28822819/212921608-ec6017e4-4e07-417d-a679-2ae71cb9e95e.png)

Although your system visually gives a relatively big circle for your thumb, we actually consider your thumb a point but not a region. You may adjust the resources and add your own selection handle style to better experience. Or just modifying the output selection handle rectangle to expand the predicate region is fine.
For more information, see `SelectionHandleStyle` and `HandleStyleSideDrop`.

**Comment by radimitrov** [comment]
HandleStyleSideDrop scaling doesn't appear to work but HandleStyleDrop does. However I think it helps on my test device.

**Comment by massivemadness** [comment]
The selection handle is uncomfortable to use because it's size is smaller than the original `EditText` handle. It would be better if @Rosemoe could increase the selection handle area

![Screenshot_2022-06-07-22-25-11-593_com blacksquircle ui](https://user-images.githubusercontent.com/7825871/215698501-b96d8bf3-40d3-4860-9394-17bd7658a437.jpg)

**Comment by Rosemoe** [comment]
> The selection handle is uncomfortable to use because it's size is smaller than the original `EditText` handle. It would be better if @Rosemoe could increase the selection handle area
> 
> ![Screenshot_2022-06-07-22-25-11-593_com blacksquircle ui](https://user-images.githubusercontent.com/7825871/215698501-b96d8bf3-40d3-4860-9394-17bd7658a437.jpg)


Fine. I'll expand the area for action detection
