### ISSUE TITLE
Add configurable top scroll margin

### ISSUE THREAD

**Issue by radimitrov** [Rosemoe/sora-editor#359]
Currently there is a bottom over scroll margin like you can see in the first screenshot.
I'm suggesting adding a configurable top margin (default 0) like illustrated in the second screenshot.
That would allow overlaying some potentially IDE related UI elements without affecting the editor's ability to show all lines.
![Screenshot_2023-01-17-13-29-16-401_com example soraeditortest](https://user-images.githubusercontent.com/56889141/212890178-3bb0e72f-552c-479d-a82a-f8ce8b03b3b9.jpg)
![Screenshot_2023-01-17-13-36-53-089_com example soraeditortest](https://user-images.githubusercontent.com/56889141/212890195-6e51990b-14bd-4157-9a83-65ff723e1d8a.jpg)

**Comment by Rosemoe** [comment]
You should make it by correctly organize your layout instead of requesting editor to add this margin. For instance, You may view AndroidIDE and CodeAssit.
We have no plan for view padding/inner margin now.

**Comment by radimitrov** [comment]
I'm only asking because I've seen it implemented in other (web) editors.
The implementations of AndroidIDE, CodeAssit won't work for my case. Not without the same layout overlay issues they have.
This method was the most optimal but I will find another if it won't be implemented.
