### ISSUE TITLE
Sora editor implementation

### ISSUE THREAD

**Issue by TechnicalStudioDeveloper** [Rosemoe/sora-editor#375]
@Rosemoe I am creating a project using the Sketchware pro and i have to add code editor in it but there is not documentation for that that is why I need your help to implement Sora editor in my sketchware project
I need HTML,CSS,JS,Java,XML,JSON language in editor and 2 themes dark and light.Then I want to publish it in github.

**Comment by TechnicalStudioDevelopers** [comment]
If I ask for code of sora editor then you can provide me?

**Comment by TechnicalStudioDevelopers** [comment]
Because there is no documentation.

**Comment by Rosemoe** [comment]
Documentation won't be so ABC to illustrate how to include the library in every programming tools.
Why SketchwarePro successufully used the library without the 'documentation' you need? The library is published to maven central as mentioned in README.
Besides, the code of the whole library is in this repository, **completely open**.

**Comment by TechnicalStudioDevelopers** [comment]
Why I can't able to write in Sora-editor 
[Video](https://dl.dropbox.com/s/fv2lkj4whzswjhx/Screenrecorder-2023-02-10-15-06-27-232%280%29.mp4?dl=0)

**Comment by TechnicalStudioDevelopers** [comment]
> Why I can't able to write in Sora-editor [Video](https://dl.dropbox.com/s/fv2lkj4whzswjhx/Screenrecorder-2023-02-10-15-06-27-232%280%29.mp4?dl=0)

@Rosemoe I also can't able to paste.

**Comment by TechnicalStudioDevelopers** [comment]
Oh! It was my mistake.
