### ISSUE TITLE
Add Sort/Arrangements for Access Modifiers, Fields

### ISSUE THREAD

**Issue by SnowAkira09876** [Rosemoe/sora-editor#379]
I love a feature in IntelliJ/Eclipse where it can sort and arrange the access modifiers or fields from public-protected-private or make the order alphabetically. Is it possible here? Thank you Developers.

**Comment by Rosemoe** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/28822819/218303656-5ba18ce1-c28b-4351-aeb3-8ad4ef996d02.png)

**Comment by SnowAkira09876** [comment]
Bro can you do it🙂 I've been looking that feature everywhere. I just wanted to organize my code. I really wanted to sort my methods, fields from public to private and even an option to sort them alphabetically😬

**Comment by MrIkso** [comment]
@SnowAkira09876 it's related to your code formatter, it not problem sora editor. See exits open source java code formatter

**Comment by Rosemoe** [comment]
> Bro can you do it🙂 I've been looking that feature everywhere. I just wanted to organize my code. I really wanted to sort my methods, fields from public to private and even an option to sort them alphabetically😬

That's not what editor library will do. You should implement the feature on your own.
