### ISSUE TITLE
NullPointerException in GrammarRegistry.getInstance().loadGrammars

### ISSUE THREAD

**Issue by asm-01** [Rosemoe/sora-editor#386]
This may caught when the grammar(or)languageConfiguration path from languages.json doesn't exist.

And about the performance, it's take some times to load grammers depending on how much languages you add to load. It's freezing the UI a bit (in my case 20 languages and it takes more than 5s)

**Comment by Rosemoe** [comment]
I'll fix the problem soon.

For the second issue, you may load grammars asynchronously.

**Comment by asm-01** [comment]
I'm aware of that solution for second issues. However, I don't understand the demo code due to lack of knowledge about kotlin.
