### ISSUE TITLE
How to listen for text changes?

### ISSUE THREAD

**Issue by khaled-0** [Rosemoe/sora-editor#387]
Hi, thanks for making this awesome project.

Currently there's no way of knowing when the contents if the editor are edited. (I couldn't find any)

Is this possible to implement please.

For example, When we edit the text it would be nice to show some visual indicators about the edits and various other stuffs. Which I currently don't see any way of accomplishing.

Thanks

**Comment by Rosemoe** [comment]
Use CodeEditor#subscribeEvent with ContentChangeEvent.

**Comment by PranavPurwar** [comment]
@khaled-0 you can use `ContentListener` and `CodeEditor.getText().addContentListener(listener)` to listen for text changes

**Comment by khaled-0** [comment]
TODO: Document this in the demo or somewhere
