### ISSUE TITLE
Git Diffy Parse

### ISSUE THREAD

**Issue by AndroXStudiO** [Rosemoe/sora-editor#400]
![Screenshot_2023-03-11-01-27-30-76_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/88816748/224462090-8c615eb6-4bea-4fb2-af13-719e26a7c315.jpg)
is it possible to git - diffy parse like this?

**Comment by Rosemoe** [comment]
Of course it is possible. But it is unplanned: we are not to implement everything.
