### ISSUE TITLE
Gboard related issue after cutting text

### ISSUE THREAD

**Issue by Raival-e** [Rosemoe/sora-editor#401]
This happens when I cut a piece of code using Gboard (I tried FlorisBoard and there were no issues). You can see that it removes a piece of code right after I type something (I think the code that gets removed has same length as the one copied, I could be wrong though). I'm using the latest demo app (v0.21.1) from GitHub actions.

https://user-images.githubusercontent.com/81700082/226181463-d4d4ede8-f5c7-428f-a2cf-b38a4a5bded1.mp4

**Comment by Rosemoe** [comment]
Thanks for you feedback. I'll fix this bug later.
