### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by moderGamer** [Rosemoe/sora-editor#425]
I am using version 0.9.0, it prints Arabic texts in reverse. Can you tell me which class I should update to the latest version to solve this problem?

**Comment by Rosemoe** [comment]
It's almost impossible to update a single file to support RTL texts in sora-editor. So no suggestion will be given.
We strongly recommend using newest editor version released.

**Comment by moderGamer** [comment]
> 

I can't do it like this, I'll lose all the languages ​​I've made, and Textmeta can't replace the produced languages, which means it doesn't have a proper behavior pattern.

**Comment by moderGamer** [comment]
> 

Yes, I checked, in fact, it has completely changed. I wanted to replace them, but I couldn't. I suggest adding the language file of the previous versions to reduce the pain of creating the previous languages. I don't think it will be difficult. It is also a Java file, you can do it  find it in version 0.9.0 dev1 and add it, this way your work will be solved and the rest is not a good idea?

**Comment by Rosemoe** [comment]
> > Previously provided languages in 0.8.4 or earlier will not be added. You may write adapter to make the legacy languages work but that's meaningless because we prefer to use textmate or tree-sitter to get a better experience with enhanced syntax-highlighting and completions.
> 
> Yes, it's true, but it still doesn't work well. I'll give you an example. Test it yourself and see if the keywords don't work well. You can check the installation file.
> 
> https://github.com/Visual-Code-Space/Visual-Code-Space

The author used custom language class that extends TextmateLanguage but disabled the auto-completion. That's not our editor library issue. You may download AndroidIDE or CodeAssist to see if the completion works well.

**Comment by moderGamer** [comment]
> 

Yes, they use server languages. This one, TextMeta, only colors the text. It does not suggest these keywords. I suggest you avoid complex codes. I have been working in Java for 5 years. I checked your codes. You code is very complicated.  As I have so much experience in programming, I got confused
