### ISSUE TITLE
Add support for customizing background color in symbol input button.

### ISSUE THREAD

**Issue by asm-01** [Rosemoe/sora-editor#428]
Something like to be able to used surface color from material themes. In light mode that doesn't effect anything but in dark the buttons color are dark while theme have different surfaces like dark blue or whatever so it doesn't look good at all

**Comment by Rosemoe** [comment]
We can not satisfy this requirement because the editor does not actually embed the material library.
You may set color of the `SymbolInputView` direcctly by `View#setBackgroundColor` on activity initialization.
