### ISSUE TITLE
How to add icon to the line

### ISSUE THREAD

**Issue by abodinagdat16** [Rosemoe/sora-editor#431]
I want to customise the line by adding icon on it ..how can I do that?

**Comment by Rosemoe** [comment]
Icons can only be added from language analyzers currently in editor. See `LineSideIcon`, `LineAnchorStyle`, `LineStyles` and `AnalyzeManager` for more information.

**Comment by abodinagdat16** [comment]
Ok ...thanks...how sora editor can read big files? Do you use Thread or what for reading and displaying the content on it?

**Comment by Rosemoe** [comment]
> Ok ...thanks...how sora editor can read big files? Do you use Thread or what for reading and displaying the content on it?

This is managed by your application. We provide `ContentIO` to read a stream into a new `Content` object.

**Comment by abodinagdat16** [comment]
Thanks
