### ISSUE TITLE
EDITOR-LSP error in server side due to absolute uri passed by client

### ISSUE THREAD

**Issue by STICKnoLOGIC** [Rosemoe/sora-editor#442]
I found out that everytime I try to connect to my php lsp (phpactor) using this lib throw an error on my server side due to not absolute uri/file path...

trying to debug and searching the source code leads me to URIUtils in io/github/rosemoe/sora/lsp/utils....

the expected uri/String path should be:
file:///path/to/workplace

but I end up getting:
file:/path/to/workspace

as you can see, the end result missing "//" between the path and file which cannot be parsed/access by the lsp server as its not the absolute file/path.

phone: android 9, vivo v9, not rooted, all storage permission granted.

want to pr but dont have time so I make an issue instead
hope it will be fixed! TIA

**Comment by Rosemoe** [comment]
After investigation, I found that file URI without host name can be simplified to 'file:/' instead of 'file:///'. 'file:///' is actually caused by an empty host name.
