### ISSUE TITLE
[Help Wanted] Create `Content` from InputStream instead of CharSequence/String

### ISSUE THREAD

**Issue by MuntashirAkon** [Rosemoe/sora-editor#454]
I use Apache's `CharSequenceInputStream` to write texts from `Content` to a file without using any intermediary String, thereby, reducing the memory usage. Now, I want to do the same for reading texts into `Content`. I know that it is not possible, but I need a hint on how to start. Here it's probable that I may not be able to use `BufferedInputStream#readLine()` because the line separator is also needed.

**Comment by Rosemoe** [comment]
See `ContentIO` for creating a `Content` object from streams.

**Comment by MuntashirAkon** [comment]
Thanks.
