### ISSUE TITLE
@drawable/magnifier _background Not Found

### ISSUE THREAD

**Issue by TeamEvils150** [Rosemoe/sora-editor#461]
aapt: No resource found write to that matches the given name (at 'background' with value '@drawable/magnifier _background').

**Comment by Rosemoe** [comment]
Check you resources.

**Comment by TeamEvils150** [comment]
There is no Drawable folder (I am using AIDE)
![Screenshot_20230721-163147](https://github.com/Rosemoe/sora-editor/assets/139203005/0c3f71b1-dd35-4990-a624-224b26b2ae46)

**Comment by Rosemoe** [comment]
Your AAR file is broken. Or your AIDE just does not build. 

We do not recommend using AIDE. Use Gradle build systems.
