### ISSUE TITLE
Sticky scroll window should be hidden on select all

### ISSUE THREAD

**Issue by PranavPurwar** [Rosemoe/sora-editor#468]
When we are selecting text, the sticky scroll window should be hidden
![Screenshot_2023-08-13-19-15-14-448_org cosmicide rewrite](https://github.com/Rosemoe/sora-editor/assets/75154889/c601b099-6baa-4f21-a369-405d6225a346)

**Comment by Rosemoe** [comment]
Now the sticky scroll panel hides (partially or fully) when there is any text selected in visible region to make selected text visible. However, if there is no visible selected text in screen, it still shows.
Do you think it's fine?

**Comment by PranavPurwar** [comment]
Yeah, should be fine I think.
