### ISSUE TITLE
The code or text does not appear when using EditorColorScheme

### ISSUE THREAD

**Issue by abodinagdat16** [Rosemoe/sora-editor#483]
In my app and also in the sample app when I use `EditorColorScheme` the code getting invisible like in this video:

https://github.com/Rosemoe/sora-editor/assets/69758268/79d8df00-ffe6-42f3-a991-857b57352380

**Comment by Rosemoe** [comment]
Please note that textmate works only when color scheme is compatible with textmate.
In sample app, color schemes with 'for TM' suffix are applicable when using textmate languages. Using other schemes will lead to invisible texts.

**Comment by abodinagdat16** [comment]
ok and also how can i change symbol input view background color?

**Comment by abodinagdat16** [comment]
Ok, thanks 👍
