### ISSUE TITLE
Add OCaml language

### ISSUE THREAD

**Issue by NathanFallet** [Rosemoe/sora-editor#52]
Hello there,
I would like to add support for OCaml language to this editor.
I already have a lexer for this language written in Swift here: https://github.com/GroupeMINASTE/OCaml-iOS/blob/main/OCaml/Models/OCamlLexer.swift
I saw the wiki, I will try to make a PR in coming weeks to implement this language myself.

**Comment by Rosemoe** [comment]
Thanks for your contributions!

**Comment by NathanFallet** [comment]
@Rosemoe Is there any way to generate the language plugin if we have some grammar files? I saw how it is implemented for python, java, etc... and it seems to be very long if it has to be done by hand

**Comment by Rosemoe** [comment]
You can use ANTLR or JFlex
