### ISSUE TITLE
TM4E copyright/license headers changed

### ISSUE THREAD

**Issue by sebthom** [Rosemoe/sora-editor#537]
Dear @Rosemoe,

while looking for showcases for the [Eclipse TM4E](https://github.com/eclipse/tm4e/) project I came across your nice Sora Editor.

Unfortunately I realized that you changed the copyright/license header of all files under https://github.com/Rosemoe/sora-editor/tree/main/language-textmate/src/main/java/org/eclipse/tm4e/languageconfiguration

I'd kindly ask you to revert this change and retain the original copyright/license header.

Thanks a lot in advance!

p.s. You can also consult the EPL Q&A page at https://www.eclipse.org/legal/epl-2.0/faq.php if you have further questions

**Comment by Rosemoe** [comment]
I'm really sorry for the license violation due to my mistake during handling those files from TM4E.

We will fix the copyright headers in related files as soon as possible. Sorry for the mistake again and thanks for the issue!
