### ISSUE TITLE
Enhance text selection method

### ISSUE THREAD

**Issue by Raival-e** [Rosemoe/sora-editor#54]
Hi,
the method that this editor has isn't good. it's not smooth as well as it is hard to move the cursor and many other issues compared with the default android text selection method. so it would be way better if you use the default text selection method rather than a custom one (if possible). keep in mind that it offers many editing options such as cope, paste, select all, and much more.

**Comment by itsaky** [comment]
It would be helpful if you list the issues you're facing.

**Comment by Rosemoe** [comment]
The default text selection method is private in class android.widget.Editor.
As our project is not based on TextView, it is not very pratical to use the default one. That is highly adapted to oringal widget.

**Comment by Rosemoe** [comment]
However we may learn from its code.
And, though it won't be exactly the same as system's, do you think that a selection method like MT Manager's will be nice? We're able to implement one like MT's.

**Comment by aliveness-e** [comment]
Absolutely, MT Manager's selection method is so good.
Thanks.

**Comment by Rosemoe** [comment]
Could you please describe what you want to improve in details?
Do you mean the style of handle, action popup visibility scheme and text magnifier?

**Comment by aliveness-e** [comment]
Style of handle is fine. if you can replace the current selection action with a popup action menu, that would be easier to use. also, the ability to show the action menu when we long-press (without needing to select a word) just like a normal textview. text magnifier is a good add, it would improve the experience.

**Comment by Rosemoe** [comment]
> Style of handle is fine. if you can replace the current selection action with a popup action menu, that would be easier to use. also, the ability to show the action menu when we long-press (without needing to select a word) just like a normal textview. text magnifier is a good add too, it would improve the experience.

Ok, I'll consider that
