### ISSUE TITLE
Add support for clickable spans

### ISSUE THREAD

**Issue by itsaky** [Rosemoe/sora-editor#540]
## Feature description

A special kind of span could be added to the editor to allow performing various click events (single click, double click, long click, etc) for text in the editor. This span class should contain abstract methods to handle such click events and :
- Information such as text and the text region for the span should be provided to these methods. I'm not sure if these methods should be provided with the editor instance. I would like to know your opinion on this.
- The methods must return a value indicating whether the event was consumed by the span (for example, `true` if consumed, `false` otherwise).
- If the event was not consumed, the editor could perform its usual actions.

This is much more efficient than using the existing `ClickEvent` and `DoubleClickEvent` as the analyzer could also add context-aware clickable spans.

## Use case

This special span could be used to add clickable text in the editor (for URLs or any other action in the application). An example use case is mentioned in AndroidIDEOfficial/AndroidIDE#1687.

## Possible challenges

The clickable spans may conflict with the existing click handling logic when the editor is editable. However, the implementation totally depends on the user of the library and should not be a concern for sora-editor in my opinion.

**Comment by Rosemoe** [comment]
## Pontential Problems
* Currently, `Span` object carries only style related data and extra data for language implementation internal usage (like completions and brackets matching). Adding click events in `Span` will introduce code that depends on `Context` and other UI objects. Is that what we really want?
* There will be more subclasses of `Span`, and these subclasses can not share their features. For example, `StaticColorSpan` and `AdvancedSpan` features can not be used at the same time.
## Possible Implementation
* `Span` carries `ClickableData` (interface), which indicates the span is clickable and provide context-related data in document. And we provide lazily-fetched `Span` at the clicked position in `ClickEvent`, etc. How to handle those clickable spans is up to library user, by subscribing to the event and intercepting the event accordingly.
* `Span` maintains a lazy map of uncommonly-used features. Adding a `SpanExtFeature` class to provide keys (possibly strings) of features. Feature attributes are described by related interfaces. For example, to use static color, we initialize the map and add a (SpanExtFeature.STATIC_COLOR, SpanStaticColor object) key-value pair to the map. In this way we can easily make spans with composite features. However, this is a breaking change for current `StaticColorSpan` and `AdvancedSpan` users.
  * Why not add all related fields: There are a lot of `Span` objects for a single document. More uncommonly-used fields results in significant unnecessary memory usage.

What do you think about this idea?
