### ISSUE TITLE
Crash when settingText with less lines than previous Text

### ISSUE THREAD

**Issue by RohitKushvaha01** [Rosemoe/sora-editor#562]
How to reproduce this error (this error is related to curser index out of bound)

1. setText with the ContentIO class from a input stream that is made of Uri (the text file has more than 100+ lines)

2. On the editor edit some text of the last line (keep the curser at that line)

3. setText a text with less lines breaks than before

4. Crash
[crash_log.txt](https://github.com/Rosemoe/sora-editor/files/14414027/crash_log.txt)

**Comment by Rosemoe** [comment]
I think the reproducing steps should be:
1. Set a long text from `ContentIO`, and edit on the last line
2. Set a shorter text
3. Call setText with the `Content` object we used in step 1
4. Crash

Is that right?

**Comment by RohitKushvaha01** [comment]
> I think the reproducing steps should be:
> 
> 1. Set a long text from `ContentIO`, and edit on the last line
> 2. Set a shorter text
> 3. Call setText with the `Content` object we used in step 1
> 4. Crash
> 
> Is that right?

Yes
