### ISSUE TITLE
Support Live Templates

### ISSUE THREAD

**Issue by abdelkrimkr** [Rosemoe/sora-editor#571]
Live Templates: Support for code templates and snippets that can be easily inserted and customized, reducing repetitive coding tasks.

**Comment by itsaky** [comment]
Snippets feature is already available :

https://github.com/Rosemoe/sora-editor/tree/main/editor/src/main/java/io/github/rosemoe/sora/lang/completion/snippet

**Comment by abdelkrimkr** [comment]
Yes , but not like Live templates in android studio

**Comment by Rosemoe** [comment]
I think Live Templates are based on code snippets. Live Templates are a set of code snippets for language-specific code completion. Thus, Live Templates management should be implemented by IDE apps.

**Comment by dingyi222666** [comment]
Actually, the Snippets in sora-editor are derived from those in [VSCode](https://code.visualstudio.com/docs/editor/userdefinedsnippets). They are akin to the live templates in IntelliJ IDEs. I think this feature has been implemented.

**Comment by abdelkrimkr** [comment]
@Rosemoe @dingyi222666 @itsaky Thanks for your efforts 👌.
