### ISSUE TITLE
Application Crashed

### ISSUE THREAD

**Issue by mohammad-ayan-008** [Rosemoe/sora-editor#576]
java.lang.NoSuchMethodError: No static method obtain(IJ)Lio/github/rosemoe/sora/lang/styling/Span;

Only when I use editor.setLanguage(new JavaLanguage())

Dependencies I used
implementation(platform("io.github.Rosemoe.sora-editor:bom:0.23.2"))
    implementation("io.github.Rosemoe.sora-editor:language-java")
    implementation("io.github.Rosemoe.sora-editor:editor")

**Comment by Rosemoe** [comment]
Updating to 0.23.3 or later should fix this.
