### ISSUE TITLE
Make line separator compatible with windows CRLF  = LF 

### ISSUE THREAD

**Issue by Ma7moud3ly** [Rosemoe/sora-editor#583]
I'm creating a text editor for Micropython, sometimes a user write a script in Windows and tries to edit it with my code editor.
If a text contains "\r\n\r\n\" CRLF CRLF
- in logcat (windows)
<img src="https://github.com/Rosemoe/sora-editor/assets/16342931/188eea34-472b-4c5c-b7d4-c25df11b5e55" width=400>

- ```CodeEditor``` formats it with 4 line separators..
<img src="https://github.com/Rosemoe/sora-editor/assets/16342931/bd52fd06-1708-4449-894b-8305e647cf50" width=400>

**How to consider ```\n == \r\n``` without using String.replace method**

**Comment by Rosemoe** [comment]
Loading text with ContentIO should works.
