### ISSUE TITLE
.c或.cpp文件注释的字体颜色

### ISSUE THREAD

**Issue by ms458** [Rosemoe/sora-editor#585]
在.c或.cpp文件中，希望注释的字体不要用黑色颜色，希望能像18行那样的灰白颜色
![Screenshot_2024-05-06-17-23-39-150_com.itsaky.androidide.jpg](https://github.com/Rosemoe/sora-editor/assets/108029807/dcd3c030-55fd-44b0-a0c1-557ac7e125a7)

**Comment by Rosemoe** [comment]
请向 AndroidIDE 反馈该问题。这并非由我们控制。

**Comment by ms458** [comment]
> 请向 AndroidIDE 反馈该问题。这并非由我们控制。

好的宝子，我还以为是属于编译器的呢🤔
