### ISSUE TITLE
[bug]: cannot display unicode symbols

### ISSUE THREAD

**Issue by hasanelfalakiy** [Rosemoe/sora-editor#593]
Some code editor applications that use the latest Sora Editor cannot display Unicode correctly, (rendering), I think this is because of sora editor 
![Screenshot_20240326_044305](https://github.com/Rosemoe/sora-editor/assets/96150715/e3f7c149-4887-49fc-92a1-ad385be52a87)
![Screenshot_20240326_065619](https://github.com/Rosemoe/sora-editor/assets/96150715/c6fd10e8-8b3e-4687-ad1c-693b664cf2ed)

**Comment by Rosemoe** [comment]
The editor actually display these symbols correctly.
I can not reproduce this problem if i directly paste these symbols into the editor.

**Comment by hasanelfalakiy** [comment]
> The editor actually display these symbols correctly.
> I can not reproduce this problem if i directly paste these symbols into the editor.

so is it actually a problem with the application using sora editor?

**Comment by Rosemoe** [comment]
Yes, as the screenshot below, the editor displays them well:
![6240d48489c57a56336ef66aecfef8be_720](https://github.com/user-attachments/assets/7235129a-a1ac-4a19-8896-6e10d32848ba)

**Comment by hasanelfalakiy** [comment]
> Yes, as the screenshot below, the editor displays them well:
> ![6240d48489c57a56336ef66aecfef8be_720](https://github.com/user-attachments/assets/7235129a-a1ac-4a19-8896-6e10d32848ba)
> 

oh okay
