### ISSUE TITLE
No virtual method toArray

### ISSUE THREAD

**Issue by ghost** [Rosemoe/sora-editor#599]
My app crashes when I open it and it's the error:
![Screenshot_٢٠٢٤٠٧٠٢-٠٤٢٤٣٧_AndroidIDE](https://github.com/Rosemoe/sora-editor/assets/65798784/1fad4fa4-f8c6-43ac-9d0f-d8a2a6a000ea)
![Screenshot_٢٠٢٤٠٧٠٢-٠٤٢٤٤٥_AndroidIDE](https://github.com/Rosemoe/sora-editor/assets/65798784/344ff260-2f1e-46a5-a437-835f571fcbb6)

**Used version: 0.23.4**

Error fixed when I downgraded bom version to **0.22.1**

Keep in mind that I use coreLibraryDesugaring and get the issue in the 0.23.4 version

**Comment by dingyi222666** [comment]
Use snapshot version
