### ISSUE TITLE
Curser issue

### ISSUE THREAD

**Issue by RohitKushvaha01** [Rosemoe/sora-editor#600]
When typing in a newly created editor view, the text starts appearing from the beginning of the first line instead of the cursor position.

**Steps to reproduce**:
1. Open the demo app.
2. Click on an empty line (this bug only occurs on empty lines).
3. Start typing.

https://github.com/user-attachments/assets/e9170944-fa2a-48fe-b87a-33207be42faf

**Comment by Rosemoe** [comment]
This problem is probably fixed in the latest commit (1ffd0cf).

**Comment by RohitKushvaha01** [comment]
> This problem is probably fixed in the latest commit (1ffd0cf).

Thanks
