### ISSUE TITLE
 editorSearcher.getCurrentMatchedPositionIndex() is always return -1

### ISSUE THREAD

**Issue by Testermt** [Rosemoe/sora-editor#613]
editorSearcher.getCurrentMatchedPositionIndex() this method always return -1 and i aslo try to use other method to check search result found or not but that method also not working here the method names
editorSearcher.isMatchedPositionSelected() issue always return false

editorSearcher.hasQuery() issue  always return false

**Comment by Rosemoe** [comment]
`hasQuery` returning false means that seaching text is not requested. You must first call `EditorSearcher#search` to start.

For more details of the searcher, see javadoc of its methods.
