### ISSUE TITLE
Editor waste space

### ISSUE THREAD

**Issue by RohitKushvaha01** [Rosemoe/sora-editor#629]
Recently, I tried using Sora Editor on a very large screen and noticed that enabling word wrap causes excessive unused space. Could you consider adding a method to adjust the editor's width for better utilization of screen space?

![image](https://github.com/user-attachments/assets/50a44906-e3a7-43bf-95dd-9760f41593d5)

**Comment by RohitKushvaha01** [comment]
it somehow fixed in latest version of sora

**Comment by Rosemoe** [comment]
Thanks for the feedback
