### ISSUE TITLE
Sharing a Single LSP Server Across Multiple Editors

### ISSUE THREAD

**Issue by RohitKushvaha01** [Rosemoe/sora-editor#637]
Hi, I'm trying to share a LSP server instance between multiple editors in my application. I currently initialize it with an editor like this:

```kotlin

val lspProject = LspProject(projectPath)
lspProject.addServerDefinition(luaServerDefinition)

lspEditor = lspProject.createEditor(file.absolutePath)
lspEditor!!.wrapperLanguage = createTextMateLanguage()
lspEditor!!.editor = editor


runCatching { lspEditor!!.connectWithTimeout() }


```

I think the connection should be made at the LspProject level to avoid connections for each editor. How can I modify this code to share the same LSP server across multiple editors?

Any advice would be greatly appreciated!

**Comment by dingyi222666** [comment]
`LspEditor` should be created based on `LspProject` for each different file path.

In practice, the `CodeEditor` and its attached `LspEditor` are usually created inside a `Fragment`, with each `Fragment` representing a file that has been opened and is being edited.
