### ISSUE TITLE
Add SQL Support

### ISSUE THREAD

**Issue by ShivamJoker** [Rosemoe/sora-editor#71]
Hey it would be really awesome to get SQL support, if you can guide me with a basic template I can give it a shot to create a PR.

We can grab the words and color schemes from highlight.js as well - https://github.com/highlightjs/highlight.js/blob/main/src/languages/sql.js

**Comment by itsaky** [comment]
CodeEditor uses lexer to highlight to code. You can use lexer and parser generators like JFlex and ANTLR4 to generate a lexer.

For implementation example, see [HTMLAnalyzer](https://github.com/Rosemoe/CodeEditor/blob/main/language-html/src/main/java/io/github/rosemoe/editor/langs/html/HTMLAnalyzer.java) or [PythonCodeAnalyzer](https://github.com/Rosemoe/CodeEditor/blob/main/language-python/src/main/java/io/github/rosemoe/editor/langs/python/PythonCodeAnalyzer.java). Both of these analyzers use lexer generated using ANTLR4.

You can write your own lexer too. See [JavaTokenizer](https://github.com/Rosemoe/CodeEditor/blob/main/language-java/src/main/java/io/github/rosemoe/editor/langs/java/JavaTextTokenizer.java) and [JavaCodeAnalyzer](https://github.com/Rosemoe/CodeEditor/blob/main/language-java/src/main/java/io/github/rosemoe/editor/langs/java/JavaCodeAnalyzer.java).

For simple languages, you can implement a [LanguageDescription](https://github.com/Rosemoe/CodeEditor/blob/main/language-universal/src/main/java/io/github/rosemoe/editor/langs/universal/LanguageDescription.java). For implementation examples, see [this](https://github.com/Rosemoe/CodeEditor/tree/main/language-universal/src/main/java/io/github/rosemoe/editor/langs/desc).
